CREATE TABLE User (
    Id INT NOT NULL AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(50),
    PasswordHash TEXT NOT NULL,
    Role VARCHAR(50) NOT NULL,
    Rating DOUBLE NOT NULL,
    Service VARCHAR(255),
    PRIMARY KEY (Id),
    UNIQUE INDEX (Email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;